import { test, expect } from '../fixtures/test-env';
import { getTestCreds } from '../helpers/test-creds';

// All credentials are dynamically generated by global-setup.ts

test.describe('Phase 1 - Real Matrix SDK Integration', () => {

    test('login with real credentials succeeds', async ({ harness }) => {
        const creds = getTestCreds();
        await harness.loadWasm();
        await harness.connect(creds.homeserverUrl);

        const result = await harness.login(
            creds.user1.token, creds.user1.userId, creds.user1.deviceId
        );
        expect(result.ok).toBe(true);
        expect(result.loggedIn).toBe(true);
    });

    test('login with invalid token fails', async ({ harness }) => {
        const creds = getTestCreds();
        await harness.loadWasm();
        await harness.connect(creds.homeserverUrl);

        try {
            await harness.login('invalid_token', creds.user1.userId, 'fake_device');
        } catch (e: any) {
            expect(e.message).toMatch(/Login failed|Failed to verify|Unknown access token/);
        }
    });

    test('get rooms after login', async ({ harness }) => {
        const creds = getTestCreds();
        await harness.loadWasm();
        await harness.connect(creds.homeserverUrl);
        await harness.login(
            creds.user1.token, creds.user1.userId, creds.user1.deviceId
        );

        const result = await harness.getRooms();
        expect(result.ok).toBe(true);
        expect(Array.isArray(result.rooms)).toBe(true);
        const testRoom = result.rooms.find(
            (r: any) => r.roomId === creds.roomId
        );
        expect(testRoom).toBeTruthy();
    });

    test('send a message to test room', async ({ harness }) => {
        const creds = getTestCreds();
        await harness.loadWasm();
        await harness.connect(creds.homeserverUrl);
        await harness.login(
            creds.user1.token, creds.user1.userId, creds.user1.deviceId
        );

        const result = await harness.sendMessage(
            creds.roomId,
            'Hello from Phase 1 integration test!'
        );
        expect(result.ok).toBe(true);
        expect(result.eventId).toBeTruthy();
        console.log('Sent message, event ID:', result.eventId);
    });

    test('sync receives events', async ({ harness }) => {
        const creds = getTestCreds();
        await harness.loadWasm();
        await harness.connect(creds.homeserverUrl);
        await harness.login(
            creds.user1.token, creds.user1.userId, creds.user1.deviceId
        );

        await harness.startSync();
        await harness.sendMessage(creds.roomId, 'Sync test ' + Date.now());
        await new Promise(r => setTimeout(r, 3000));

        const eventsResult = await harness.getEvents(0);
        console.log(`Received ${eventsResult.totalCount} events during sync`);
        await harness.stopSync();
    });

    // Skip: logout invalidates token and parallel test workers may interfere.
    // Logout functionality is verified in Phase 2 worker tests.
    test.skip('logout clears session', async ({ harness }) => {
        const creds = getTestCreds();
        await harness.loadWasm();
        await harness.connect(creds.homeserverUrl);
        // Use user2 for logout test to avoid invalidating user1's token
        // which other tests may be using in parallel
        await harness.login(
            creds.user2.token, creds.user2.userId, creds.user2.deviceId
        );

        const result = await harness.logout();
        expect(result.ok).toBe(true);

        const session = await harness.getSessionInfo();
        expect(session.isLoggedIn).toBe(false);
    });
});
