// Test credential loader.
// Reads credentials generated by global-setup.ts.
// All test specs should import from here instead of hardcoding tokens.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CREDS_FILE = path.resolve(__dirname, '..', '.test-creds.json');

interface TestCreds {
    homeserverUrl: string;
    user1: { token: string; userId: string; deviceId: string };
    user2: { token: string; userId: string; deviceId: string };
    roomId: string;
}

let _creds: TestCreds | null = null;

export function getTestCreds(): TestCreds {
    if (_creds) return _creds;

    if (!fs.existsSync(CREDS_FILE)) {
        throw new Error(
            `Test credentials not found at ${CREDS_FILE}. ` +
            'Run `npx playwright test` (global-setup will create them) or ' +
            'check that the Matrix homeserver is running.'
        );
    }

    _creds = JSON.parse(fs.readFileSync(CREDS_FILE, 'utf-8'));
    return _creds!;
}

export const HOMESERVER = () => getTestCreds().homeserverUrl;
export const USER1 = () => getTestCreds().user1;
export const USER2 = () => getTestCreds().user2;
export const ROOM_ID = () => getTestCreds().roomId;
